In [1]:
# vectorization example
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("for loop: " + str(1000*(toc-tic)) + "ms")

249969.35042622726
Vectorized version: 1.4493465423583984ms
249969.3504262469
for loop: 513.9269828796387ms


In [14]:
# broadcasting example
A = np.array([[56,0,4.4,68],
              [1.2,104,52,8],
              [1.8,135,99,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [15]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [17]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [20]:
# python-numpy vectors
a = np.random.randn(5) # this is neither a row vector nor a col vector
                       # this is a "rank 1 array"
print(a)
print(a.shape)
print(a.T)

[ 0.65409413 -1.64217235  0.90925035  0.58697079 -0.5017652 ]
(5,)
[ 0.65409413 -1.64217235  0.90925035  0.58697079 -0.5017652 ]


In [21]:
print(a,a.T)

[ 0.65409413 -1.64217235  0.90925035  0.58697079 -0.5017652 ] [ 0.65409413 -1.64217235  0.90925035  0.58697079 -0.5017652 ]


In [24]:
# use the following way but not the above "rank 1 array"
a = np.random.rand(5,1)
print(a)
print(a.T)

[[0.57625501]
 [0.94476897]
 [0.78083477]
 [0.26860434]
 [0.08698553]]
[[0.57625501 0.94476897 0.78083477 0.26860434 0.08698553]]


In [25]:
print(np.dot(a,a.T)) # outer product

[[0.33206983 0.54442785 0.44995994 0.1547846  0.05012585]
 [0.54442785 0.8925884  0.73770846 0.25376905 0.08218123]
 [0.44995994 0.73770846 0.60970294 0.20973561 0.06792132]
 [0.1547846  0.25376905 0.20973561 0.07214829 0.02336469]
 [0.05012585 0.08218123 0.06792132 0.02336469 0.00756648]]


In [28]:
print(np.dot(a.T,a)) # inner product

[[1.91407595]]


In [32]:
assert(a.shape == (5,1)) 
# it assumes a.shape is 5 by 1; 
# if it is false, assert will throw errors